schema_version = "1.0.0"

id = "voronoi_scatter"
version = "1.13.0"
name = "Scattershot"
tagline = "Quickly distributes image textures around your model with several controls for randomization"
maintainer = "Jonathan Lampel (Orange Turbine) <jlampel@autotroph.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
# permissions = []

# Optional link to documentation, support, source files, etc
website = "https://jlampel.github.io/voronoi_scatter/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Material", "Node"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "6.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2024 Jonathan Lampel, Autotroph Inc"
]